package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="froze"
)
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nome;
     private Integer idade;
     private Date dataNascimento;
     private String genero;
     private String estadoCivil;
     private String telefone;
     private String cell;
     private String email;
     private String naturalidade;
     private Set<Venda> vendas = new HashSet<Venda>(0);

    public Cliente() {
    }
    
     public Cliente(String nome, Integer idade, Date dataNascimento, String genero, String estadoCivil, String telefone, String cell, String email, String naturalidade) {
       this.nome = nome;
       this.idade = idade;
       this.dataNascimento = dataNascimento;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.telefone = telefone;
       this.cell = cell;
       this.email = email;
       this.naturalidade = naturalidade;
       //this.vendas = vendas;
    }

    public Cliente(String nome, Integer idade, Date dataNascimento, String genero, String estadoCivil, String telefone, String cell, String email, String naturalidade, Set<Venda> vendas) {
       this.nome = nome;
       this.idade = idade;
       this.dataNascimento = dataNascimento;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.telefone = telefone;
       this.cell = cell;
       this.email = email;
       this.naturalidade = naturalidade;
       this.vendas = vendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcliente", unique=true, nullable=false)
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="idade")
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="genero", length=45)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="estado_civil", length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="telefone", length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cell", length=45)
    public String getCell() {
        return this.cell;
    }
    
    public void setCell(String cell) {
        this.cell = cell;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="naturalidade", length=45)
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Venda> getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set<Venda> vendas) {
        this.vendas = vendas;
    }




}


