package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entradas generated by hbm2java
 */
@Entity
@Table(name="entradas"
    ,catalog="froze"
)
public class Entradas  implements java.io.Serializable {


     private Integer identradas;
     private Date dataEntrada;
     private Integer qtdAnterior;
     private Integer qtdPosterior;
     private Integer quantAcrescentad;
     private Set<Produto> produtos = new HashSet<Produto>(0);

    public Entradas() {
    }

    public Entradas(Date dataEntrada, Integer qtdAnterior, Integer qtdPosterior, Integer quantAcrescentad) {
       this.dataEntrada = dataEntrada;
       this.qtdAnterior = qtdAnterior;
       this.qtdPosterior = qtdPosterior;
       this.quantAcrescentad = quantAcrescentad;
       //this.produtos = produtos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="identradas", unique=true, nullable=false)
    public Integer getIdentradas() {
        return this.identradas;
    }
    
    public void setIdentradas(Integer identradas) {
        this.identradas = identradas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_entrada", length=19)
    public Date getDataEntrada() {
        return this.dataEntrada;
    }
    
    public void setDataEntrada(Date dataEntrada) {
        this.dataEntrada = dataEntrada;
    }

    
    @Column(name="qtd_anterior")
    public Integer getQtdAnterior() {
        return this.qtdAnterior;
    }
    
    public void setQtdAnterior(Integer qtdAnterior) {
        this.qtdAnterior = qtdAnterior;
    }

    
    @Column(name="qtd_posterior")
    public Integer getQtdPosterior() {
        return this.qtdPosterior;
    }
    
    public void setQtdPosterior(Integer qtdPosterior) {
        this.qtdPosterior = qtdPosterior;
    }

    
    @Column(name="quant_acrescentad")
    public Integer getQuantAcrescentad() {
        return this.quantAcrescentad;
    }
    
    public void setQuantAcrescentad(Integer quantAcrescentad) {
        this.quantAcrescentad = quantAcrescentad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entradas")
    public Set<Produto> getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set<Produto> produtos) {
        this.produtos = produtos;
    }




}


