package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name="fornecedor"
    ,catalog="froze"
)
public class Fornecedor  implements java.io.Serializable {


     private Integer idfornecedor;
     private String nome;
     private Integer idade;
     private String documento;
     private String cidade;
     private String telefone;
     private String cell;
     private String email;
     private String rua;
     private String quarteirao;
     private String bairro;
     private Set<Produtofornecedor> produtofornecedors = new HashSet<Produtofornecedor>(0);

    public Fornecedor() {
    }
    
     public Fornecedor(String nome, Integer idade, String documento, String cidade, String telefone, String cell, String email, String rua, String quarteirao, String bairro) {
       this.nome = nome;
       this.idade = idade;
       this.documento = documento;
       this.cidade = cidade;
       this.telefone = telefone;
       this.cell = cell;
       this.email = email;
       this.rua = rua;
       this.quarteirao = quarteirao;
       this.bairro = bairro;
       //this.produtofornecedors = produtofornecedors;
    }

    public Fornecedor(String nome, Integer idade, String documento, String cidade, String telefone, String cell, String email, String rua, String quarteirao, String bairro, Set<Produtofornecedor> produtofornecedors) {
       this.nome = nome;
       this.idade = idade;
       this.documento = documento;
       this.cidade = cidade;
       this.telefone = telefone;
       this.cell = cell;
       this.email = email;
       this.rua = rua;
       this.quarteirao = quarteirao;
       this.bairro = bairro;
       this.produtofornecedors = produtofornecedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idfornecedor", unique=true, nullable=false)
    public Integer getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(Integer idfornecedor) {
        this.idfornecedor = idfornecedor;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="idade")
    public Integer getIdade() {
        return this.idade;
    }
    
    public void setIdade(Integer idade) {
        this.idade = idade;
    }

    
    @Column(name="documento", length=45)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    
    @Column(name="cidade", length=45)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="telefone", length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cell", length=45)
    public String getCell() {
        return this.cell;
    }
    
    public void setCell(String cell) {
        this.cell = cell;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="rua", length=45)
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    
    @Column(name="quarteirao", length=45)
    public String getQuarteirao() {
        return this.quarteirao;
    }
    
    public void setQuarteirao(String quarteirao) {
        this.quarteirao = quarteirao;
    }

    
    @Column(name="bairro", length=45)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedor")
    public Set<Produtofornecedor> getProdutofornecedors() {
        return this.produtofornecedors;
    }
    
    public void setProdutofornecedors(Set<Produtofornecedor> produtofornecedors) {
        this.produtofornecedors = produtofornecedors;
    }




}


