package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produtofornecedor generated by hbm2java
 */
@Entity
@Table(name="produtofornecedor"
    ,catalog="froze"
)
public class Produtofornecedor  implements java.io.Serializable {


     private ProdutofornecedorId id;
     private Fornecedor fornecedor;
     private Produto produto;
     private String pro;

    public Produtofornecedor() {
    }

	
    public Produtofornecedor(ProdutofornecedorId id, Fornecedor fornecedor, Produto produto) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.produto = produto;
    }
    public Produtofornecedor(ProdutofornecedorId id, Fornecedor fornecedor, Produto produto, String pro) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.pro = pro;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="produtoIdproduto", column=@Column(name="produto_idproduto", nullable=false) ), 
        @AttributeOverride(name="fornecedorIdfornecedor", column=@Column(name="fornecedor_idfornecedor", nullable=false) ) } )
    public ProdutofornecedorId getId() {
        return this.id;
    }
    
    public void setId(ProdutofornecedorId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor_idfornecedor", nullable=false, insertable=false, updatable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_idproduto", nullable=false, insertable=false, updatable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    
    @Column(name="pro", length=45)
    public String getPro() {
        return this.pro;
    }
    
    public void setPro(String pro) {
        this.pro = pro;
    }




}


