package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Produtovenda generated by hbm2java
 */
@Entity
@Table(name="produtovenda"
    ,catalog="froze"
)
public class Produtovenda  implements java.io.Serializable {


     private int produtoIdproduto;
     private Produto produto;
     private Venda venda;
     private Double subTotal;
     private int quantidadeProdutos;

    public Produtovenda() {
    }

	
    public Produtovenda(Produto produto, Venda venda, int quantidadeProdutos) {
        this.produto = produto;
        this.venda = venda;
        this.quantidadeProdutos = quantidadeProdutos;
    }
    public Produtovenda(Produto produto, Venda venda, Double subTotal, int quantidadeProdutos) {
       this.produto = produto;
       this.venda = venda;
       this.subTotal = subTotal;
       this.quantidadeProdutos = quantidadeProdutos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="produto"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="produto_idproduto", unique=true, nullable=false)
    public int getProdutoIdproduto() {
        return this.produtoIdproduto;
    }
    
    public void setProdutoIdproduto(int produtoIdproduto) {
        this.produtoIdproduto = produtoIdproduto;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venda_idvenda", nullable=false)
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    
    @Column(name="subTotal", precision=22, scale=0)
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }

    
    @Column(name="quantidadeProdutos", nullable=false)
    public int getQuantidadeProdutos() {
        return this.quantidadeProdutos;
    }
    
    public void setQuantidadeProdutos(int quantidadeProdutos) {
        this.quantidadeProdutos = quantidadeProdutos;
    }




}


