package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutofornecedorId generated by hbm2java
 */
@Embeddable
public class ProdutofornecedorId  implements java.io.Serializable {


     private int produtoIdproduto;
     private int fornecedorIdfornecedor;

    public ProdutofornecedorId() {
    }

    public ProdutofornecedorId(int produtoIdproduto, int fornecedorIdfornecedor) {
       this.produtoIdproduto = produtoIdproduto;
       this.fornecedorIdfornecedor = fornecedorIdfornecedor;
    }
   


    @Column(name="produto_idproduto", nullable=false)
    public int getProdutoIdproduto() {
        return this.produtoIdproduto;
    }
    
    public void setProdutoIdproduto(int produtoIdproduto) {
        this.produtoIdproduto = produtoIdproduto;
    }


    @Column(name="fornecedor_idfornecedor", nullable=false)
    public int getFornecedorIdfornecedor() {
        return this.fornecedorIdfornecedor;
    }
    
    public void setFornecedorIdfornecedor(int fornecedorIdfornecedor) {
        this.fornecedorIdfornecedor = fornecedorIdfornecedor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutofornecedorId) ) return false;
		 ProdutofornecedorId castOther = ( ProdutofornecedorId ) other; 
         
		 return (this.getProdutoIdproduto()==castOther.getProdutoIdproduto())
 && (this.getFornecedorIdfornecedor()==castOther.getFornecedorIdfornecedor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProdutoIdproduto();
         result = 37 * result + this.getFornecedorIdfornecedor();
         return result;
   }   


}


