package modelo;
// Generated Nov 17, 2016 12:19:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="froze"
)
public class Produto  implements java.io.Serializable {


     private Integer idproduto;
     private Entradas entradas;
     private String nome;
     private Integer quantidadeUnit;
     private String categoria;
     private Double precoVenda;
     private String tipoProduto;
     private Date dataEntrada;
     private Integer quantidadeGrosso;
     private Produtovenda produtovenda;
     private Set<Produtofornecedor> produtofornecedors = new HashSet<Produtofornecedor>(0);

    public Produto() {
    }

	
    public Produto(Entradas entradas) {
        this.entradas = entradas;
    }
    
    public Produto(Entradas entradas, String nome, Integer quantidadeUnit, String categoria, Double precoVenda, String tipoProduto, Date dataEntrada, Integer quantidadeGrosso) {
       this.entradas = entradas;
       this.nome = nome;
       this.quantidadeUnit = quantidadeUnit;
       this.categoria = categoria;
       this.precoVenda = precoVenda;
       this.tipoProduto = tipoProduto;
       this.dataEntrada = dataEntrada;
       this.quantidadeGrosso = quantidadeGrosso;
       //this.produtovenda = produtovenda;
       //this.produtofornecedors = produtofornecedors;
    }
    
    public Produto(Entradas entradas, String nome, Integer quantidadeUnit, String categoria, Double precoVenda, String tipoProduto, Date dataEntrada, Integer quantidadeGrosso, Produtovenda produtovenda, Set<Produtofornecedor> produtofornecedors) {
       this.entradas = entradas;
       this.nome = nome;
       this.quantidadeUnit = quantidadeUnit;
       this.categoria = categoria;
       this.precoVenda = precoVenda;
       this.tipoProduto = tipoProduto;
       this.dataEntrada = dataEntrada;
       this.quantidadeGrosso = quantidadeGrosso;
       this.produtovenda = produtovenda;
       this.produtofornecedors = produtofornecedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproduto", unique=true, nullable=false)
    public Integer getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(Integer idproduto) {
        this.idproduto = idproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entradas_identradas", nullable=false)
    public Entradas getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Entradas entradas) {
        this.entradas = entradas;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="quantidade_unit")
    public Integer getQuantidadeUnit() {
        return this.quantidadeUnit;
    }
    
    public void setQuantidadeUnit(Integer quantidadeUnit) {
        this.quantidadeUnit = quantidadeUnit;
    }

    
    @Column(name="categoria", length=45)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="preco_venda", precision=22, scale=0)
    public Double getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(Double precoVenda) {
        this.precoVenda = precoVenda;
    }

    
    @Column(name="tipo_produto", length=45)
    public String getTipoProduto() {
        return this.tipoProduto;
    }
    
    public void setTipoProduto(String tipoProduto) {
        this.tipoProduto = tipoProduto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_entrada", length=10)
    public Date getDataEntrada() {
        return this.dataEntrada;
    }
    
    public void setDataEntrada(Date dataEntrada) {
        this.dataEntrada = dataEntrada;
    }

    
    @Column(name="quantidade_grosso")
    public Integer getQuantidadeGrosso() {
        return this.quantidadeGrosso;
    }
    
    public void setQuantidadeGrosso(Integer quantidadeGrosso) {
        this.quantidadeGrosso = quantidadeGrosso;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="produto")
    public Produtovenda getProdutovenda() {
        return this.produtovenda;
    }
    
    public void setProdutovenda(Produtovenda produtovenda) {
        this.produtovenda = produtovenda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produto")
    public Set<Produtofornecedor> getProdutofornecedors() {
        return this.produtofornecedors;
    }
    
    public void setProdutofornecedors(Set<Produtofornecedor> produtofornecedors) {
        this.produtofornecedors = produtofornecedors;
    }




}


